//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ql_nhanvien_form.ql_nhanvien_service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nhanvien", Namespace="http://schemas.datacontract.org/2004/07/ql_nhanvien")]
    [System.SerializableAttribute()]
    public partial class Nhanvien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gioitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string luongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phongbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tennvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gioitinh {
            get {
                return this.gioitinhField;
            }
            set {
                if ((object.ReferenceEquals(this.gioitinhField, value) != true)) {
                    this.gioitinhField = value;
                    this.RaisePropertyChanged("gioitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string luong {
            get {
                return this.luongField;
            }
            set {
                if ((object.ReferenceEquals(this.luongField, value) != true)) {
                    this.luongField = value;
                    this.RaisePropertyChanged("luong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string manv {
            get {
                return this.manvField;
            }
            set {
                if ((object.ReferenceEquals(this.manvField, value) != true)) {
                    this.manvField = value;
                    this.RaisePropertyChanged("manv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phongban {
            get {
                return this.phongbanField;
            }
            set {
                if ((object.ReferenceEquals(this.phongbanField, value) != true)) {
                    this.phongbanField = value;
                    this.RaisePropertyChanged("phongban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sdt {
            get {
                return this.sdtField;
            }
            set {
                if ((object.ReferenceEquals(this.sdtField, value) != true)) {
                    this.sdtField = value;
                    this.RaisePropertyChanged("sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tennv {
            get {
                return this.tennvField;
            }
            set {
                if ((object.ReferenceEquals(this.tennvField, value) != true)) {
                    this.tennvField = value;
                    this.RaisePropertyChanged("tennv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thuong {
            get {
                return this.thuongField;
            }
            set {
                if ((object.ReferenceEquals(this.thuongField, value) != true)) {
                    this.thuongField = value;
                    this.RaisePropertyChanged("thuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ql_nhanvien_service.Iql_nhanvien_service")]
    public interface Iql_nhanvien_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/getAll", ReplyAction="http://tempuri.org/Iql_nhanvien_service/getAllResponse")]
        ql_nhanvien_form.ql_nhanvien_service.Nhanvien[] getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/getAll", ReplyAction="http://tempuri.org/Iql_nhanvien_service/getAllResponse")]
        System.Threading.Tasks.Task<ql_nhanvien_form.ql_nhanvien_service.Nhanvien[]> getAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/search", ReplyAction="http://tempuri.org/Iql_nhanvien_service/searchResponse")]
        ql_nhanvien_form.ql_nhanvien_service.Nhanvien[] search(int manv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/search", ReplyAction="http://tempuri.org/Iql_nhanvien_service/searchResponse")]
        System.Threading.Tasks.Task<ql_nhanvien_form.ql_nhanvien_service.Nhanvien[]> searchAsync(int manv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/create", ReplyAction="http://tempuri.org/Iql_nhanvien_service/createResponse")]
        void create(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/create", ReplyAction="http://tempuri.org/Iql_nhanvien_service/createResponse")]
        System.Threading.Tasks.Task createAsync(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/update", ReplyAction="http://tempuri.org/Iql_nhanvien_service/updateResponse")]
        void update(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/update", ReplyAction="http://tempuri.org/Iql_nhanvien_service/updateResponse")]
        System.Threading.Tasks.Task updateAsync(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/delete", ReplyAction="http://tempuri.org/Iql_nhanvien_service/deleteResponse")]
        void delete(int manv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iql_nhanvien_service/delete", ReplyAction="http://tempuri.org/Iql_nhanvien_service/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(int manv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iql_nhanvien_serviceChannel : ql_nhanvien_form.ql_nhanvien_service.Iql_nhanvien_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iql_nhanvien_serviceClient : System.ServiceModel.ClientBase<ql_nhanvien_form.ql_nhanvien_service.Iql_nhanvien_service>, ql_nhanvien_form.ql_nhanvien_service.Iql_nhanvien_service {
        
        public Iql_nhanvien_serviceClient() {
        }
        
        public Iql_nhanvien_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iql_nhanvien_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iql_nhanvien_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iql_nhanvien_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ql_nhanvien_form.ql_nhanvien_service.Nhanvien[] getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<ql_nhanvien_form.ql_nhanvien_service.Nhanvien[]> getAllAsync() {
            return base.Channel.getAllAsync();
        }
        
        public ql_nhanvien_form.ql_nhanvien_service.Nhanvien[] search(int manv) {
            return base.Channel.search(manv);
        }
        
        public System.Threading.Tasks.Task<ql_nhanvien_form.ql_nhanvien_service.Nhanvien[]> searchAsync(int manv) {
            return base.Channel.searchAsync(manv);
        }
        
        public void create(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt) {
            base.Channel.create(manv, tennv, phongban, gioitinh, luong, thuong, sdt);
        }
        
        public System.Threading.Tasks.Task createAsync(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt) {
            return base.Channel.createAsync(manv, tennv, phongban, gioitinh, luong, thuong, sdt);
        }
        
        public void update(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt) {
            base.Channel.update(manv, tennv, phongban, gioitinh, luong, thuong, sdt);
        }
        
        public System.Threading.Tasks.Task updateAsync(int manv, string tennv, string phongban, string gioitinh, int luong, int thuong, int sdt) {
            return base.Channel.updateAsync(manv, tennv, phongban, gioitinh, luong, thuong, sdt);
        }
        
        public void delete(int manv) {
            base.Channel.delete(manv);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int manv) {
            return base.Channel.deleteAsync(manv);
        }
    }
}
