//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _251_DinhQuangTung_Form.DinhQuangTung_251_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Benxe", Namespace="http://schemas.datacontract.org/2004/07/_251_DinhQuangTung")]
    [System.SerializableAttribute()]
    public partial class Benxe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loaixeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maxeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soluongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenxeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loaixe {
            get {
                return this.loaixeField;
            }
            set {
                if ((object.ReferenceEquals(this.loaixeField, value) != true)) {
                    this.loaixeField = value;
                    this.RaisePropertyChanged("loaixe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maxe {
            get {
                return this.maxeField;
            }
            set {
                if ((object.ReferenceEquals(this.maxeField, value) != true)) {
                    this.maxeField = value;
                    this.RaisePropertyChanged("maxe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((object.ReferenceEquals(this.soluongField, value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenxe {
            get {
                return this.tenxeField;
            }
            set {
                if ((object.ReferenceEquals(this.tenxeField, value) != true)) {
                    this.tenxeField = value;
                    this.RaisePropertyChanged("tenxe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DinhQuangTung_251_Service.I251_DinhQuangTung_Service")]
    public interface I251_DinhQuangTung_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/getAll", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/getAllResponse")]
        _251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[] getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/getAll", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/getAllResponse")]
        System.Threading.Tasks.Task<_251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[]> getAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/search", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/searchResponse")]
        _251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[] search(int maxe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/search", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/searchResponse")]
        System.Threading.Tasks.Task<_251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[]> searchAsync(int maxe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/create", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/createResponse")]
        void create(int maxe, string tenxe, int soluong, string loaixe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/create", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/createResponse")]
        System.Threading.Tasks.Task createAsync(int maxe, string tenxe, int soluong, string loaixe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/update", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/updateResponse")]
        void update(int maxe, string tenxe, int soluong, string loaixe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/update", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/updateResponse")]
        System.Threading.Tasks.Task updateAsync(int maxe, string tenxe, int soluong, string loaixe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/delete", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/deleteResponse")]
        void delete(int maxe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I251_DinhQuangTung_Service/delete", ReplyAction="http://tempuri.org/I251_DinhQuangTung_Service/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(int maxe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I251_DinhQuangTung_ServiceChannel : _251_DinhQuangTung_Form.DinhQuangTung_251_Service.I251_DinhQuangTung_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I251_DinhQuangTung_ServiceClient : System.ServiceModel.ClientBase<_251_DinhQuangTung_Form.DinhQuangTung_251_Service.I251_DinhQuangTung_Service>, _251_DinhQuangTung_Form.DinhQuangTung_251_Service.I251_DinhQuangTung_Service {
        
        public I251_DinhQuangTung_ServiceClient() {
        }
        
        public I251_DinhQuangTung_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I251_DinhQuangTung_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I251_DinhQuangTung_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I251_DinhQuangTung_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[] getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<_251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[]> getAllAsync() {
            return base.Channel.getAllAsync();
        }
        
        public _251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[] search(int maxe) {
            return base.Channel.search(maxe);
        }
        
        public System.Threading.Tasks.Task<_251_DinhQuangTung_Form.DinhQuangTung_251_Service.Benxe[]> searchAsync(int maxe) {
            return base.Channel.searchAsync(maxe);
        }
        
        public void create(int maxe, string tenxe, int soluong, string loaixe) {
            base.Channel.create(maxe, tenxe, soluong, loaixe);
        }
        
        public System.Threading.Tasks.Task createAsync(int maxe, string tenxe, int soluong, string loaixe) {
            return base.Channel.createAsync(maxe, tenxe, soluong, loaixe);
        }
        
        public void update(int maxe, string tenxe, int soluong, string loaixe) {
            base.Channel.update(maxe, tenxe, soluong, loaixe);
        }
        
        public System.Threading.Tasks.Task updateAsync(int maxe, string tenxe, int soluong, string loaixe) {
            return base.Channel.updateAsync(maxe, tenxe, soluong, loaixe);
        }
        
        public void delete(int maxe) {
            base.Channel.delete(maxe);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int maxe) {
            return base.Channel.deleteAsync(maxe);
        }
    }
}
